// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npmptzfqhjmhndrtwqdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbXB0emZxaGptaG5kcnR3cWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzOTIwNTEsImV4cCI6MjA2NDk2ODA1MX0.2g1l-rQ1I-2biWeGEdTRVnqUJhTl_-QjNV2zdyikoxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);